name: 'Publish Alpha Build'
description: 'This action will generate a distribution and upload it to PyPI'
inputs:
  action_branch:
    description: 'The shared action branch to checkout'
    required: false
    default: 'main'
  version_file:
    description: 'The file location to read the version from'
    required: false
    default: 'version.py'
  python_version:
    description: 'The python version to use'
    required: false
    default: '3.8'
  changelog_file:
    description: 'The file location of the changelog'
    required: false
    default: 'CHANGELOG.md'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: dev
        path: action/package/
    - name: Checkout Scripts Repo
      uses: actions/checkout@v4
      with:
        repository: OpenVoiceOS/.github
        ref: ${{ inputs.action_branch }}
        path: action/github/
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Increment Version
      shell: bash
      run: |
        python action/github/scripts/bump_alpha.py
        VERSION=$(python action/package/setup.py --version)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: "Generate release changelog"
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GH_PAT }}
        output: action/package/${{ inputs.changelog_file }}
    - name: Push Version Change
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Increment Version to ${{ env.VERSION }}
        repository: action/package/
    - name: Change working directory to release
      shell: bash
      run: cd ${{ github.workspace }}/action/package/
    - name: Create Pre-release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_PAT }}
        tag: V${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: |
          Changes in this Release
          ${{ steps.changelog.outputs.changelog }}
        commit: dev
        prerelease: true
    - name: Install Build Tools
      shell: bash
      run: |
        pip install --upgrade pip
        python -m pip install build wheel
    - name: Build Distribution Packages
      shell: bash
      run: |
        cd action/package
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{secrets.PYPI_TOKEN}}
        packages-dir: action/package/dist/