name: 'Bump Version (after testing QA started)'
description: 'This action bumps the version after the testing QA phase has started'
inputs:
  action_branch:
    description: 'The shared action branch to checkout'
    required: false
    default: 'main'
  python_version:
    description: 'The python version to use'
    required: false
    default: '3.8'
  version_file:
    description: 'The file location to read the version from'
    required: false
    default: 'version.py'
  changelog_file:
    description: 'The file location of the changelog'
    required: false
    default: 'CHANGELOG.md'
  subject:
    description: 'Subject title of the push/pull-request event to parse the release type.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: set up release type
      shell: bash
      run: |
        RELEASE_TYPE=$(echo "${{ inputs.subject }}" | grep -oP '(patch|minor|major)')
        echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
    - name: Checkout Package
      uses: actions/checkout@v4
      with:
        ref: dev
        fetch-depth: 0
        path: action/package
    - name: Checkout Scripts Repo
      uses: actions/checkout@v4
      with:
        repository: OpenVoiceOS/.github
        ref: ${{ inputs.action_branch }}
        path: action/github/
    - name: Set up python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Common Python Requirements
      run: |
        pip install -r ${{ github.workspace }}/action/github/requirements/pip_base.txt
    - name: alpha_release
      uses: ./action/github/.github/actions/release_alpha
      with:
        action_branch: ${{ inputs.action_branch }}
        python_version: ${{ inputs.python_version }}
        version_file: ${{ inputs.version_file }}
        changelog_file: ${{ inputs.changelog_file }}
    - name: Bump to next ${{ env.RELEASE_TYPE }} version
        id: version
        run: |
          cd ${{ github.workspace }}/action/github/scripts/
          VERSION=$(python semver_release_version.py --file ${{ env.VERSION_FILE }})
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          NEXT_VERSION=$(python semver_release_version.py --next --file ${{ env.VERSION_FILE }} --release ${{ env.RELEASE_TYPE }} --save)
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
    - name: Push Version Change (${{ env.VERSION }} -> ${{ env.NEXT_VERSION }})
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Increment Version to ${{ env.NEXT_VERSION }}
        repository: action/package/
    - name: Rebase testing onto dev
      shell: bash
      run: |
        cd ${{ github.workspace }}/action/package/
        git checkout testing
        git rebase dev
        git push origin testing --force
    - name: Notify Matrix Room
      uses: ./action/github/.github/actions/notify_testing_matrix
      with:
        kickoff_pr: false
        release_type: ${{ env.RELEASE_TYPE }}
