name: Auto translate
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ${{ github.ref }}
      locale_folder:
        type: string
        default: "locale"

jobs:
  autotranslate:
    env:
      API_KEY: ${{secrets.DL_API_KEY}}
      LOCALE_FOLDER: ${{ github.workspace }}/action/package/${{ inputs.locale_folder }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v3
        with:
          repository: OpenVoiceOS/.github
          path: action/github/
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Translate Tools
        run: |
          python -m pip install ovos-translate-plugin-deepl ovos-utils
      - name: Auto Translate
        run: |
          python action/github/scripts/translate.py
      - name: Commit to dev
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: autotranslate
          repository: action/package/
