name: License Tests
on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'
      branch:
        description: 'Branch to check out'
        type: string
        default: ${{ github.ref }}

jobs:
  validate-pr-title:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.1.0
        with:
          token: ${{ secrets.GH_PAT }}
          task_types: '["feat", "fix", "docs", "test", "ci", "refactor", "perf", "chore", "revert", "translation"]'
          custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "housekeeping", "revert": "revert", "wip": "WIP"}'