name: License Tests
on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'
      branch:
        description: 'Branch to check out'
        type: string
        default: ${{ github.ref }}
      action_branch:
        description: 'Branch to check out'
        type: string
        default: main
      custom_labels:
        description: 'Custom labels to use'
        type: string
      pr_number:
        description: 'Optional pull request number'
        type: number
      missing_cc_error:
        description: 'Throws an error if the title not adheres to Conventional Commit format'
        type: boolean
        default: true

jobs:
  validate-pr-title:
    runs-on: ${{ inputs.runner }}
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      PR_LABELS: ${{ inputs.custom_labels }}
      PR_NUMBER: ${{ inputs.pr_number }}
    steps:
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements/pip_base.txt
      - name: Status Check
        run: |
          python scripts/check_PRs.py
        