name: Notify Matrix Chat

# only triggers on pull request closed events
on:
  workflow_call:
    inputs:
      pr_id:
        type: number
        required: true

jobs:
  notify_pr_matrix:
    runs-on: ubuntu-latest
    env:
      PACKAGE: "$(basename ${{ github.repository }})"
    steps:
      - uses: actions/checkout@v4
      - name: Send message to Matrix bots channel
        id: matrix-chat-message
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.org'
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: '!WjxEKjjINpyBRPFgxl:krbel.duckdns.org'
          message: |
            new ${{ env.PACKAGE }} PR merged! https://github.com/${{ github.repository }}/pull/${{ inputs.pr_id }}