name: Propose Translation
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: ${{ github.ref_name }}
      python_version:
        type: string
        default: "3.8"
      language:
        type: string
        default: ""
      locale_folder:
        type: string
        default: "locale"
      reviewer:
        type: string
        default: "emphasize"
      

jobs:
  Propose_translation:
    env:
      TARGET_LANG: ${{ inputs.language }}
      API_KEY: ${{ secrets.DL_API_KEY }}
      LOCALE_FOLDER: ${{ github.workspace }}/action/package/${{ inputs.locale_folder }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        path: action/package/
    - name: Checkout Scripts Repo
      uses: actions/checkout@v4
      with:
        repository: OpenVoiceOS/.github
        path: action/github/
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Translate Tools
      run: |
        python -m pip install ovos-translate-plugin-deepl ovos-utils
    - name: Run Translate Script
      run: |
        python action/github/scripts/translate.py
        cd ${{ github.workspace }}/action/package/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: autotranslate
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: Proposed ${{ inputs.language }} Translations
        body: Translations for review
        labels: translation
        branch: staging/translation_${{ inputs.language }}
        reviewers: ${{ inputs.reviewer }}
