# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build ...aX
on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to checkout and run the action in'
        type: string
        default: ${{ github.ref }}
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      version_file:
        description: 'The file location to read the version from'
        type: string
        default: version.py
      python_version:
        description: 'The python version to use'
        type: string
        default: "3.8"
      locale_folder:
        description: 'The base folder to look for localization files'
        type: string
        default: locale
      changelog_file:
        type: string
        default: CHANGELOG.md

jobs:
  autotranslate:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.DL_API_KEY}} 
      LOCALE_FOLDER: ${{ github.workspace }}/action/package/${{ inputs.locale_folder }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          working-directory: action/package/
          filters: |
            locales:
              - '${{ env.LOCALE_FOLDER }}/en-us/**'
              - '${{ env.LOCALE_FOLDER }}/../dialog/en-us/**'
              - '${{ env.LOCALE_FOLDER }}/../vocab/en-us/**'
      - name: Setup Python
        if: steps.filter.outputs.locales == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Auto Translate
        if: steps.filter.outputs.locales == 'true'
        run: |
          python -m pip install -r action/github/requirements/pip_translation.txt
          python action/github/scripts/translate.py
      - name: Commit to dev
        if: steps.filter.outputs.locales == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: autotranslate
          repository: action/package/
    
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ${{ github.workspace }}/action/package/${{ inputs.version_file }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Increment Version
        id: version
        run: |
          python action/github/scripts/bump_alpha.py
          VERSION=$(python action/package/setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: "Generate release changelog"
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: action/package/${{ inputs.changelog_file }}
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version to ${{ env.VERSION }}
          repository: action/package/
      - name: Change working directory to release
        run: cd ${{ github.workspace }}/action/package/
      - name: Create Pre-release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: V${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            Changes in this Release
            ${{ steps.changelog.outputs.changelog }}
          commit: ${{ inputs.branch }}
          prerelease: true
      - name: Install Build Tools
        run: |
          pip install --upgrade pip
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          cd action/package
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}
          packages-dir: action/package/dist/
