name: Publish Stable Build
on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
    inputs:
      python_version:
        description: "Python version to use for the build process."
        type: string
        default: "3.8"
      changelog_file:
        description: "File to write the changelog to."
        type: string
        default: CHANGELOG.md

jobs:
  build_and_publish:
    env:
      SOURCE_BRANCH: ${{ inputs.release_type == 'build' && 'testing' || 'stable' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SOURCE_BRANCH }}
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.python_version}}
      - name: Get Version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Check Latest Release
        id: latest_release
        continue-on-error: true
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: draft,prerelease
      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: action/package/${{ inputs.changelog_file }}
          sinceTag: ${{ steps.latest_release.outputs.release }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: V${{ env.version }}
          name: Release ${{ env.version }}
          body: |
            Changes in this Release
            ${{ steps.changelog.outputs.changelog }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}
