name: Publish SemVer Build
on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true
    inputs:
      branch:
        description: 'The branch to checkout'
        type: string
        default: master
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      python_version:
        description: "Python version to use for the build process."
        type: string
        default: "3.8"
      changelog_file:
        description: "File to write the changelog to."
        type: string
        default: CHANGELOG.md
      subject:
        description: 'Subject title of the push/pull-request event to parse the release type.'
        type: string
        required: true

jobs:
  build_and_publish:
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GH_PAT: ${{ secrets.GH_PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: set up release type
        run: |
          RELEASE_TYPE=$(echo ${{ inputs.subject }} | grep -oP '(patch|minor|major)')
          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.python_version}}
      - name: Install Python Dependencies
        run: |
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_base.txt
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_build_tools.txt
      - name: Get Version
        run: |
          VERSION=$(python ${{ github.workspace }}/action/package/setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Check Latest Release
        run: |
          SINCE_TAG=$(python ${{ github.workspace }}/action/github/scripts/semver_release_version.py --latest)
          echo "SINCE_TAG=${SINCE_TAG}" >> $GITHUB_ENV
      - name: create release changelog (cropped)
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_PAT }}
          sinceTag: ${{ env.SINCE_TAG }}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            Changes in this Release
            ${{ steps.changelog.outputs.changelog }}
      - name: Build Distribution Packages
        run: |
          mkdir -p ${{ github.workspace }}/action/dist
          cd ${{ github.workspace }}/action/package/
          python setup.py sdist bdist_wheel --dist-dir ${{ github.workspace }}/action/dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}
          packages-dir: action/dist/
      # NO REBASE APPROACH!!
      # - name: Rebase dev onto master
      #   run: |
      #     cd ${{ github.workspace }}/action/package
      #     git checkout dev
      #     git rebase master
      #     git push origin dev --force
