name: Kickoff Testing Release
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: dev
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      python_version:
        description: 'The python version to use'
        type: string
        default: "3.8"
      version_file:
        description: 'The file location to read the version from'
        type: string
        default: version.py
      release_type:
        type: string
        description: 'The type of release to make'
      subject:
        type: string
        description: 'Subject title of the push/pull request event to parse the release type.'
        required: false
      locale_folder:
        type: string
        description: 'The folder location of the locale files'
        required: false
      update_intentfile:
        type: string
        description: 'The file location of the intent test file to update'
        required: false
      changelog_file:
        type: string
        description: 'The file location of the changelog'
        default: CHANGELOG.md

jobs:
  parse_conventional_commits:
    outputs:
      release_type: ${{ steps.parse.outputs.release_type }}
      was_pr: ${{ steps.parse.outputs.was_pr }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
          fetch-depth: 0
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - name: Set up python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Common System Dependencies
        run: |
          sudo apt update
          xargs sudo apt install -y < ${{ github.workspace }}/action/github/requirements/sys_deb_common_deps.txt
      - name: Install Common Python Requirements
        run: |
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_base.txt
      # check if the last commit was due to a PR merge (needed below)
      - name: PR merge?
        run: |
          cd  ${{ github.workspace }}/action/package/
          LAST_COMMIT_SHA=$(git rev-parse HEAD)
          PR_NUMBER=$(curl --silent --show-error --header "Authorization: Bearer ${{ secrets.GH_PAT }}" "https://api.github.com/repos/${{ github.repository }}/commits/${LAST_COMMIT_SHA}/pulls" | jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            echo "was_pr=true" >> $GITHUB_OUTPUT
          else
            echo "was_pr=false" >> $GITHUB_OUTPUT
          fi
      - name: Parse Conventional Commits
        id: parse
        run: |
          export TITLE="${{ inputs.subject }}"
          cd ${{ github.workspace }}/action/github
          RELEASE_TYPE=$(python scripts/parse_semver_release.py)
          echo "release_type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
  autotranslate:
    needs: parse_conventional_commits
    runs-on: ubuntu-latest
    outputs:
      translated: ${{ steps.changes.outputs.translated }}
    permissions:
      contents: write
    env:
      API_KEY: ${{secrets.DL_API_KEY}} 
      LOCALE_FOLDER: ${{ github.workspace }}/action/package/${{ inputs.locale_folder }}
      INTENT_TEST_FILE: ${{ github.workspace }}/action/package/${{ inputs.update_intentfile }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - uses: dorny/paths-filter@v2
        if: ${{ inputs.locale_folder != '' }}
        id: filter
        with:
          working-directory: action/package/
          filters: |
            us_specific:
              - '${{ inputs.locale_folder }}/en-us/**'
              - '${{ inputs.locale_folder }}/../dialog/en-us/**'
              - '${{ inputs.locale_folder }}/../vocab/en-us/**'
            general:
              - '${{ inputs.locale_folder }}/**'
              - '${{ inputs.locale_folder }}/../dialog/**'
              - '${{ inputs.locale_folder }}/../vocab/**'
      - name: Setup Python
        if: steps.filter.outputs.general == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Python Requirements
        if: steps.filter.outputs.general == 'true'
        run: |
          python -m pip install -r action/github/requirements/pip_translation.txt
      - name: Pull latest changes
        if: steps.filter.outputs.general == 'true'
        run: |
          git pull origin ${{ inputs.branch }}
      - name: Auto Translate
        if: steps.filter.outputs.general == 'true'
        run: |
          python action/github/scripts/translate.py
      # 0 if no changes were made, 1 if changes were made
      - name: changes made?
        id: changes
        run: |
          cd ${{ github.workspace }}/action/package/
          git diff --exit-code
          echo "translated=$?" >> $GITHUB_OUTPUT
      - name: Commit autotranslation to ${{ inputs.branch }}
        if: steps.changes.outputs.translated == '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(localisation): autotranslate common languages"
          repository: action/package/
          branch: ${{ inputs.branch }}
      - name: update resource test file
        if: steps.changes.outputs.translated == '1' && inputs.update_intentfile != ''
        run: |
          python action/github/scripts/update_intent_testfile.py
      - name: Commit resource test file changes to ${{ inputs.branch }}
        if: steps.changes.outputs.translated == '1' && inputs.update_intentfile != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(localisation): update resource test file"
          repository: action/package/
          branch: ${{ inputs.branch }}
  # alpha release (+ testing)
  alpha_release:
    needs: [parse_conventional_commits, autotranslate]
    if: (contains(fromJson('["patch", "minor", "major", "alpha", "release"]'), needs.parse_conventional_commits.outputs.release_type)) || (contains(fromJson('["patch", "minor", "major", "alpha"]'), inputs.release_type))
    uses: openvoiceos/.github/.github/workflows/release_alpha.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: ${{ inputs.action_branch }}
      version_file: ${{ inputs.version_file }}
      python_version: ${{ inputs.python_version }}
      changelog_file: ${{ inputs.changelog_file }}
      release_type: ${{ needs.parse_conventional_commits.outputs.release_type == 'release' && needs.parse_conventional_commits.outputs.release_type || 'alpha' }}
  # >= patch release
  kickoff_testing:
    needs: [parse_conventional_commits, alpha_release, autotranslate]
    if: (contains(fromJson('["patch", "minor", "major"]'), needs.parse_conventional_commits.outputs.release_type) || (inputs.release_type != 'alpha' && inputs.release_type != ''))
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: 'testing'
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      VERSION_FILE: ${{ github.workspace}}/action/package/${{ inputs.version_file }}
      RELEASE_TYPE: ${{ needs.parse_conventional_commits.outputs.release_type }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout Package Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ inputs.branch }}
          path: action/package/
          fetch-depth: 0
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
          path: action/github/
      - name: Install Common System Dependencies
        run: |
          sudo apt update
          xargs sudo apt install -y < ${{ github.workspace }}/action/github/requirements/sys_deb_common_deps.txt
      - name: Authenticate GitHub CLI
        run: |
          unset GITHUB_TOKEN
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
      - name: Set up python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Common Python Requirements
        run: |
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_base.txt
      - name: Bump to next ${{ env.RELEASE_TYPE }} version
        run: |
          cd ${{ github.workspace }}/action/package/
          git checkout ${{ inputs.branch }}
          VERSION=$(python setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          cd ${{ github.workspace }}/action/github/scripts/
          NEXT_VERSION=$( python semver_release_version.py --next --file ${{ env.VERSION_FILE }} --type ${{ env.RELEASE_TYPE }} --save )
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Push Version Change (${{ env.VERSION }} -> ${{ env.NEXT_VERSION }})
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Increment Version to ${{ env.NEXT_VERSION }}
          repository: action/package/
      - name: Force Push dev to testing branch
        run: |
          cd ${{ github.workspace }}/action/package/
          git push origin dev:testing --force
      # set cached test status to active
      - name: Set test status
        run: |
          echo "testing" > test-status
      - name: Cache test status
        uses: actions/cache@v2
        with:
          path: test-status
          key: test-status-${{ github.run_id }}
          restore-keys: |
            test-status-
      - name: Notify Matrix Room
        uses: ./action/github/.github/actions/notify_testing_matrix
        with:
          matrix_token: ${{ secrets.MATRIX_TOKEN }}
          subject: ${{ inputs.subject }}
          release_type: ${{ env.RELEASE_TYPE }}
          version: ${{ env.NEXT_VERSION }}
  # testing release
  # note: autotranslate as dependency requires the job running without restrictions!
  cherry_pick_testing:
    needs: [parse_conventional_commits, alpha_release, autotranslate]
    if: ${{ needs.parse_conventional_commits.outputs.release_type == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev
          path: action/package/dev/
      - name: Checkout testing branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          ref: testing
          path: action/package/testing/
      # based on the workflow run, set the number of commits to cherry pick
      # testing PRs/pushes get an alpha release for sure
      - name: set commits num to cherry pick
        run: |
          COMMITS = 1
          if [ "${{ needs.parse_conventional_commits.outputs.was_pr }}" == "true" ]; then
            COMMITS = $((COMMITS + 2))
          else
            COMMITS = $((COMMITS + 1))
          fi
          if [ "${{ needs.autotranslate.outputs.translated }}" == "1" ]; then
            COMMITS = $((COMMITS + 1))
          fi
          echo "COMMITS=${COMMITS}" >> $GITHUB_ENV
      - name: Cherry pick n last commit from dev
        run: |
          cd action/package/testing/
          git cherry-pick $(git -C ../dev log -n ${{ env.COMMITS }} --pretty=format:"%H")
      - name: Push changes to testing branch
        run: |
          cd action/package/testing/
          git push origin testing
