name: Bump Version (after testing QA started) and announce testing phase

# only triggers on pull request closed events
on:
  workflow_call:
    inputs:
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      python_version:
        description: 'The python version to use'
        type: string
        default: "3.8"
      version_file:
        description: 'The file location to read the version from'
        type: string
        default: version.py
      changelog_file:
        type: string
        default: CHANGELOG.md
      subject:
        type: string
        description: 'Subject title of the push/pull-request event to parse the release type.'
        required: true

jobs:
  alpha_release:
    secrets: inherit
    uses: openvoiceos/.github/.github/workflows/release_alpha.yml@feat/shared_actions1
    with:
      action_branch: ${{ inputs.action_branch }}
      python_version: ${{ inputs.python_version }}
      version_file: ${{ inputs.version_file }}
      changelog_file: ${{ inputs.changelog_file }}
  bump_version_and_announce_testing:
    needs: alpha_release
    env:
      VERSION_FILE: ${{ github.workspace }}/action/package/${{ inputs.version_file }}
      SOURCE_BRANCH: 'testing'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: set up release type
        run: |
          RELEASE_TYPE=$(echo ${{ inputs.subject }} | grep -oP '(patch|minor|major)')
          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - name: Increment Version
        id: version
        run: |
          python action/github/scripts/bump_${{ env.RELEASE_TYPE }}.py
          VERSION=$(python action/package/setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Increment Version to ${{ env.VERSION }}
          repository: action/package/
      # fetch the latest changes from the dev branch
      - name: Rebase testing onto dev
        run: |
          git checkout ${{ env.SOURCE_BRANCH }}
          git rebase dev
          git push origin ${{ env.SOURCE_BRANCH }} --force
      - name: Notify Matrix Room
        uses: ./action/github/.github/workflows/notify_testing_matrix.yml
        with:
          kickoff_pr: false
          release_type: ${{ env.RELEASE_TYPE }}
