name: Bump Version (after testing QA started)

# only triggers on pull request closed events
on:
  workflow_call:
    inputs:
      version_file:
        description: 'The file location to read the version from'
        type: string
        default: version.py
      subject:
        type: string
        description: 'Subject title of the push/pull-request event to parse the release type.'
        required: true

jobs:
  start_testing_phase:
    env:
      VERSION_FILE: ${{ github.workspace }}/action/package/${{ inputs.version_file }}
      SOURCE_BRANCH: 'testing'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: set up release type
        run: |
          RELEASE_TYPE=$(echo ${{ inputs.subject }} | grep -oP '(patch|minor|major)')
          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - name: Increment Version
        id: version
        run: |
          python action/github/scripts/bump_${{ env.RELEASE_TYPE }}.py
          VERSION=$(python action/package/setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Increment Version to ${{ env.VERSION }}
          repository: action/package/
      # fetch the latest changes from the dev branch
      - name: Rebase testing onto dev
        run: |
          git checkout ${{ env.SOURCE_BRANCH }}
          git rebase dev
          git push origin ${{ env.SOURCE_BRANCH }} --force
      - name: Notify Matrix Room
        uses: ./action/github/.github/workflows/notify_testing_matrix.yml
        with:
          kickoff_pr: false
          release_type: ${{ inputs.RELEASE_TYPE }}
