name: Sync Branch 'Testing' with 'Dev'

on:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Testing
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          ref: testing
          fetch-depth: 0
          path: action/package
      - name: Synchronize testing with dev
        run: |
          cd ${{ github.workspace }}/action/package
          git pull --rebase origin dev
          if [ $? -ne 0 ]; then
            git rebase --abort
            git pull --rebase -Xtheirs origin dev
          fi
          git push -f origin testing