name: Skill Ressource Tests
on:
  workflow_call:
    inputs:
      runner:
        description: 'The runner to use'
        type: string
        default: "ubuntu-latest"
      branch:
        description: 'The branch to use'
        type: string
        default: ${{ github.ref }}
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      timeout:
        type: number
        default: 15
      system_deps:
        description: 'System dependencies (whitespace delimited) to install instead of sys_deb_common_deps.txt'
        required: false
        type: string
      python_matrix:
        description: 'Python matrix (string) to use'
        type: string
        default: '["3.8", "3.9", "3.10", "3.11"]'
      pip_packages:
        description: 'Python packages (whitespace delimited) to install instead of pip_skill_tests.txt'
        required: false
        type: string
      intent_testfile:
        description: 'Intent file to test'	
        type: string
        default: test/unittests/intent_tests.yaml
      test_padatious:
        description: 'Whether to skip padatious tests'
        type: boolean
        default: False
      test_padacioso:
        description: 'Whether to skip padacioso tests'
        type: boolean
        default: True

jobs:
  test_resources:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout }}
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_matrix) }}
    steps:
      - name: Checkout Skill Repo
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{inputs.action_branch}}
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt update
          if [ -z "${{inputs.system_deps}}" ]; then
            xargs sudo apt install -y < ${{ github.workspace }}/action/github/requirements/sys_deb_common_deps.txt
          else
            sudo apt install -y ${{inputs.system_deps}}
          fi
      - name: Install Python Skill and Requirements
        run: |
          pip install --upgrade pip
          pip install wheel "cython<3.0.0"  # TODO: cython patching https://github.com/yaml/pyyaml/issues/724
          if [ -z "${{inputs.pip_packages}}" ]; then
            pip install -r ${{ github.workspace }}/action/github/requirements/pip_skill_tests.txt
          else
            pip install ${{inputs.pip_packages}}
          fi
          cd ${{ github.workspace }}/action/skill
          pip install -e .
          PKG_NAME=$(python setup.py --name)
          export TEST_SKILL_PKG_FOLDER=$(pip show -f $PKG_NAME | grep Location | cut -d ' ' -f 2)
      - name: Test Skill Intents Padacioso
        if: ${{ inputs.test_padacioso }}
        run: |
          export INTENT_ENGINE="padacioso"
          export INTENT_TEST_FILE="${{ github.workspace }}/action/skill/${{ inputs.intent_testfile }}"
          pytest action/github/test/test_skill_resourcesV2.py
      - name: Test Skill Intents Padatious
        if: ${{ inputs.test_padatious }}
        run: |
          export INTENT_ENGINE="padatious"
          export INTENT_TEST_FILE="${{ github.workspace }}/action/skill/${{ inputs.intent_testfile }}"
          pytest action/github/test/test_skill_resourcesV2.py
      - name: Push testyaml Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update test yaml"
          repository: action/skill/
